import { Roommate, CategoryInfo, Expense, Settlement, Category } from "./types";

export const ROOMMATES: Roommate[] = [
  {
    id: "adi",
    name: "Adi Bhaiya",
    shortName: "Adi",
    room: "Room 101",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    color: "indigo",
    bgColor: "bg-indigo-50 text-indigo-700 dark:bg-indigo-950/40 dark:text-indigo-300",
    borderColor: "border-indigo-200 dark:border-indigo-800",
    textColor: "text-indigo-600 dark:text-indigo-400",
    email: "adi@flatmates.local",
  },
  {
    id: "ssr",
    name: "SSR",
    shortName: "SSR",
    room: "Room 102",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    color: "emerald",
    bgColor: "bg-emerald-50 text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-300",
    borderColor: "border-emerald-200 dark:border-emerald-800",
    textColor: "text-emerald-600 dark:text-emerald-400",
    email: "ssr@flatmates.local",
  },
  {
    id: "harsh",
    name: "Harsh",
    shortName: "Harsh",
    room: "Room 103",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    color: "amber",
    bgColor: "bg-amber-50 text-amber-700 dark:bg-amber-950/40 dark:text-amber-300",
    borderColor: "border-amber-200 dark:border-amber-800",
    textColor: "text-amber-600 dark:text-amber-400",
    email: "harsh@flatmates.local",
  },
  {
    id: "manoj",
    name: "Manoj",
    shortName: "Manoj",
    room: "Room 104",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80",
    color: "rose",
    bgColor: "bg-rose-50 text-rose-700 dark:bg-rose-950/40 dark:text-rose-300",
    borderColor: "border-rose-200 dark:border-rose-800",
    textColor: "text-rose-600 dark:text-rose-400",
    email: "manoj@flatmates.local",
  },
];

export const CATEGORIES: Record<Category, CategoryInfo> = {
  groceries: {
    id: "groceries",
    label: "Groceries",
    iconName: "ShoppingCart",
    color: "text-emerald-600",
    bgColor: "bg-emerald-50 border-emerald-200 text-emerald-700",
  },
  electricity: {
    id: "electricity",
    label: "Electricity",
    iconName: "Zap",
    color: "text-amber-600",
    bgColor: "bg-amber-50 border-amber-200 text-amber-700",
  },
  gas: {
    id: "gas",
    label: "Gas Cylinder",
    iconName: "Flame",
    color: "text-orange-600",
    bgColor: "bg-orange-50 border-orange-200 text-orange-700",
  },
  rent: {
    id: "rent",
    label: "Rent",
    iconName: "Home",
    color: "text-blue-600",
    bgColor: "bg-blue-50 border-blue-200 text-blue-700",
  },
  utilities: {
    id: "utilities",
    label: "Utilities",
    iconName: "Droplets",
    color: "text-cyan-600",
    bgColor: "bg-cyan-50 border-cyan-200 text-cyan-700",
  },
  snacks: {
    id: "snacks",
    label: "Snacks & Food",
    iconName: "Utensils",
    color: "text-purple-600",
    bgColor: "bg-purple-50 border-purple-200 text-purple-700",
  },
  transport: {
    id: "transport",
    label: "Transport",
    iconName: "Car",
    color: "text-indigo-600",
    bgColor: "bg-indigo-50 border-indigo-200 text-indigo-700",
  },
  cleaning: {
    id: "cleaning",
    label: "Cleaning & Maid",
    iconName: "Sparkles",
    color: "text-teal-600",
    bgColor: "bg-teal-50 border-teal-200 text-teal-700",
  },
  internet: {
    id: "internet",
    label: "WiFi & Internet",
    iconName: "Wifi",
    color: "text-sky-600",
    bgColor: "bg-sky-50 border-sky-200 text-sky-700",
  },
  miscellaneous: {
    id: "miscellaneous",
    label: "Miscellaneous",
    iconName: "MoreHorizontal",
    color: "text-slate-600",
    bgColor: "bg-slate-50 border-slate-200 text-slate-700",
  },
};

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: "exp-1",
    description: "Monthly Supermarket Groceries & Staples",
    amount: 1000.0,
    category: "groceries",
    paidBy: "ssr",
    date: "2026-08-14",
    splitType: "equal",
    splitAmong: ["adi", "ssr", "harsh", "manoj"],
    notes: "Atta, rice, cooking oil, spices, milk, dal",
    createdAt: "2026-08-14T10:30:00Z",
  },
  {
    id: "exp-2",
    description: "Electricity Bill (July-August Power Grid)",
    amount: 2400.0,
    category: "electricity",
    paidBy: "ssr",
    date: "2026-08-10",
    splitType: "equal",
    splitAmong: ["adi", "ssr", "harsh", "manoj"],
    isUtility: true,
    electricityMeta: {
      billingPeriod: "July 2026",
      unitsConsumed: 280,
      dueDate: "2026-08-20",
    },
    notes: "Summer AC & appliances bill",
    createdAt: "2026-08-10T14:15:00Z",
  },
  {
    id: "exp-3",
    description: "HPCL 14.2kg Domestic LPG Gas Cylinder",
    amount: 1100.0,
    category: "gas",
    paidBy: "manoj",
    date: "2026-08-08",
    splitType: "equal",
    splitAmong: ["adi", "ssr", "harsh", "manoj"],
    isUtility: true,
    gasMeta: {
      cylinderCount: 1,
      cylinderType: "14.2kg Domestic LPG",
      bookingRef: "HP-889124",
    },
    notes: "Kitchen cooking gas refill",
    createdAt: "2026-08-08T18:40:00Z",
  },
  {
    id: "exp-4",
    description: "Airtel Xstream Fiber Gigabit WiFi",
    amount: 999.0,
    category: "internet",
    paidBy: "adi",
    date: "2026-08-05",
    splitType: "equal",
    splitAmong: ["adi", "ssr", "harsh", "manoj"],
    notes: "August high-speed broadband bill",
    createdAt: "2026-08-05T20:10:00Z",
  },
  {
    id: "exp-5",
    description: "Eco-Cleaning Supplies & Flat Detergents",
    amount: 600.0,
    category: "cleaning",
    paidBy: "harsh",
    date: "2026-08-04",
    splitType: "equal",
    splitAmong: ["adi", "ssr", "harsh", "manoj"],
    notes: "Floor cleaner, dishwash liquid, mop refill",
    createdAt: "2026-08-04T09:00:00Z",
  },
  {
    id: "exp-6",
    description: "Weekend Evening Snacks & Chai",
    amount: 450.0,
    category: "snacks",
    paidBy: "adi",
    date: "2026-08-02",
    splitType: "selective",
    splitAmong: ["adi", "ssr", "harsh"],
    notes: "Samosas and sweets; Manoj was visiting hometown",
    createdAt: "2026-08-02T17:00:00Z",
  },
];

export const INITIAL_SETTLEMENTS: Settlement[] = [
  {
    id: "set-1",
    fromId: "harsh",
    toId: "ssr",
    amount: 250.0,
    date: "2026-08-06",
    status: "completed",
    note: "UPI settlement for groceries & electricity share",
    createdAt: "2026-08-06T16:00:00Z",
  },
];

